# Config file for automatic testing at travis-ci.org
language: python

matrix:
    include:
        - python: 2.7
          env: KERAS_BACKEND=tensorflow TF_VERSION=1.7 KERAS_VERSION=2.2
        - python: 2.7
          env: KERAS_BACKEND=tensorflow TF_VERSION=1.10.1 KERAS_VERSION=2.2
        - python: 3.6
          env: KERAS_BACKEND=tensorflow TF_VERSION=1.10.1 KERAS_VERSION=2.2.4
        - python: 3.6
          env: KERAS_BACKEND=tensorflow TF_VERSION=1.14.0 KERAS_VERSION=2.2.4

notifications:
  email: true

install:
  #code below copied from keras' .travis.yml
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy pytest h5py nose
  - source activate test-environment
  - pip install tensorflow==$TF_VERSION
  - pip install keras==$KERAS_VERSION

script:
- PYTHONPATH=$PWD:$PYTHONPATH py.test
